//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 09:31:12 PM CET 
//


package com.sluzbenik.SluzbenikApp.model.vakc_sistem.digitalni_zeleni_sertifikat;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.vakc_sistem.digitalni_zeleni_sertifikat package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.vakc_sistem.digitalni_zeleni_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat }
     * 
     */
    public DigitalniZeleniSertifikat createDigitalniZeleniSertifikat() {
        return new DigitalniZeleniSertifikat();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOPrimaocu }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOPrimaocu createDigitalniZeleniSertifikatPodaciOPrimaocu() {
        return new DigitalniZeleniSertifikat.PodaciOPrimaocu();
    }

    /**
     * Create an instance of {@link DigitalniZeleniSertifikat.PodaciOSertifikatu }
     * 
     */
    public DigitalniZeleniSertifikat.PodaciOSertifikatu createDigitalniZeleniSertifikatPodaciOSertifikatu() {
        return new DigitalniZeleniSertifikat.PodaciOSertifikatu();
    }

}
