//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.10 at 10:00:51 PM CET 
//


package com.imunizacija.ImunizacijaApp.model.vakc_sistem.potvrda_o_vakcinaciji;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.imunizacija.ImunizacijaApp.model.vakc_sistem.IdentifiableEntity;
import com.imunizacija.ImunizacijaApp.model.vakc_sistem.util.LicniPodaciJMBG;
import com.imunizacija.ImunizacijaApp.model.vakc_sistem.util.DozaSaUstanovom;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podaci_o_primaocu" type="{http://www.vakc-sistem.rs/util}Licni_podaci_JMBG"/>
 *         &lt;element name="Podaci_o_vakcini">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;sequence>
 *                     &lt;element name="Doza" type="{http://www.vakc-sistem.rs/util}Doza_sa_ustanovom" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                   &lt;element name="Datum_naredne_doze" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Podaci_o_potvrdi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="QRCode">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Sifra_potvrde" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOPrimaocu",
    "podaciOVakcini",
    "podaciOPotvrdi"
})
@XmlRootElement(name = "Potvrda_o_vakcinaciji")
public class PotvrdaOVakcinaciji implements IdentifiableEntity {

    @XmlElement(name = "Podaci_o_primaocu", required = true)
    protected LicniPodaciJMBG podaciOPrimaocu;
    @XmlElement(name = "Podaci_o_vakcini", required = true)
    protected PodaciOVakcini podaciOVakcini;
    @XmlElement(name = "Podaci_o_potvrdi", required = true)
    protected PodaciOPotvrdi podaciOPotvrdi;
    @XmlAttribute(name = "Sifra_potvrde", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sifraPotvrde;

    @Override
    public String toString() {
        return "PotvrdaOVakcinaciji{" +
                "podaciOPrimaocu=" + podaciOPrimaocu +
                ", podaciOVakcini=" + podaciOVakcini +
                ", podaciOPotvrdi=" + podaciOPotvrdi +
                ", sifraPotvrde=" + sifraPotvrde +
                '}';
    }

    @Override
    public String getXmlId() {
        return sifraPotvrde.toString();
    }

    @Override
    public void setXmlId(String id) {
        sifraPotvrde = new BigInteger(id);
    }

    /**
     * Gets the value of the podaciOPrimaocu property.
     * 
     * @return
     *     possible object is
     *     {@link LicniPodaciJMBG }
     *     
     */
    public LicniPodaciJMBG getPodaciOPrimaocu() {
        return podaciOPrimaocu;
    }

    /**
     * Sets the value of the podaciOPrimaocu property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicniPodaciJMBG }
     *     
     */
    public void setPodaciOPrimaocu(LicniPodaciJMBG value) {
        this.podaciOPrimaocu = value;
    }

    /**
     * Gets the value of the podaciOVakcini property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOVakcini }
     *     
     */
    public PodaciOVakcini getPodaciOVakcini() {
        return podaciOVakcini;
    }

    /**
     * Sets the value of the podaciOVakcini property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOVakcini }
     *     
     */
    public void setPodaciOVakcini(PodaciOVakcini value) {
        this.podaciOVakcini = value;
    }

    /**
     * Gets the value of the podaciOPotvrdi property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOPotvrdi }
     *     
     */
    public PodaciOPotvrdi getPodaciOPotvrdi() {
        return podaciOPotvrdi;
    }

    /**
     * Sets the value of the podaciOPotvrdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOPotvrdi }
     *     
     */
    public void setPodaciOPotvrdi(PodaciOPotvrdi value) {
        this.podaciOPotvrdi = value;
    }

    /**
     * Gets the value of the sifraPotvrde property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSifraPotvrde() {
        return sifraPotvrde;
    }

    /**
     * Sets the value of the sifraPotvrde property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSifraPotvrde(BigInteger value) {
        this.sifraPotvrde = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum_izdavanja" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="QRCode">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datumIzdavanja",
        "qrCode"
    })
    public static class PodaciOPotvrdi {

        @XmlElement(name = "Datum_izdavanja", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumIzdavanja;
        @XmlElement(name = "QRCode", required = true)
        protected String qrCode;

        /**
         * Gets the value of the datumIzdavanja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumIzdavanja() {
            return datumIzdavanja;
        }

        /**
         * Sets the value of the datumIzdavanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumIzdavanja(XMLGregorianCalendar value) {
            this.datumIzdavanja = value;
        }

        /**
         * Gets the value of the qrCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQRCode() {
            return qrCode;
        }

        /**
         * Sets the value of the qrCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQRCode(String value) {
            this.qrCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;sequence>
     *           &lt;element name="Doza" type="{http://www.vakc-sistem.rs/util}Doza_sa_ustanovom" maxOccurs="unbounded"/>
     *         &lt;/sequence>
     *         &lt;element name="Datum_naredne_doze" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doze",
        "datumNaredneDoze"
    })
    public static class PodaciOVakcini {

        @XmlElement(name = "Doza", required = true)
        protected List<DozaSaUstanovom> doze;
        @XmlElement(name = "Datum_naredne_doze")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumNaredneDoze;

        /**
         * Gets the value of the doze property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doze property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoze().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DozaSaUstanovom }
         * 
         * 
         */
        public List<DozaSaUstanovom> getDoze() {
            if (doze == null) {
                doze = new ArrayList<DozaSaUstanovom>();
            }
            return this.doze;
        }

        /**
         * Gets the value of the datumNaredneDoze property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumNaredneDoze() {
            return datumNaredneDoze;
        }

        /**
         * Sets the value of the datumNaredneDoze property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumNaredneDoze(XMLGregorianCalendar value) {
            this.datumNaredneDoze = value;
        }

    }

}
