//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 12:35:16 PM CET 
//


package com.imunizacija.ImunizacijaApp.model.vakc_sistem.saglasnost_za_imunizaciju;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.vakc_sistem.saglasnost_za_imunizaciju package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.vakc_sistem.saglasnost_za_imunizaciju
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Saglasnost }
     * 
     */
    public Saglasnost createSaglasnost() {
        return new Saglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost.OVakcinaciji }
     * 
     */
    public Saglasnost.OVakcinaciji createSaglasnostOVakcinaciji() {
        return new Saglasnost.OVakcinaciji();
    }

    /**
     * Create an instance of {@link Saglasnost.OVakcinaciji.Kontraindikacije }
     * 
     */
    public Saglasnost.OVakcinaciji.Kontraindikacije createSaglasnostOVakcinacijiKontraindikacije() {
        return new Saglasnost.OVakcinaciji.Kontraindikacije();
    }

    /**
     * Create an instance of {@link Saglasnost.Zaposlenje }
     * 
     */
    public Saglasnost.Zaposlenje createSaglasnostZaposlenje() {
        return new Saglasnost.Zaposlenje();
    }

    /**
     * Create an instance of {@link Saglasnost.SocijalnaZastita }
     * 
     */
    public Saglasnost.SocijalnaZastita createSaglasnostSocijalnaZastita() {
        return new Saglasnost.SocijalnaZastita();
    }

    /**
     * Create an instance of {@link Saglasnost.Izjava }
     * 
     */
    public Saglasnost.Izjava createSaglasnostIzjava() {
        return new Saglasnost.Izjava();
    }

    /**
     * Create an instance of {@link Saglasnost.OVakcinaciji.PodaciOLekaru }
     * 
     */
    public Saglasnost.OVakcinaciji.PodaciOLekaru createSaglasnostOVakcinacijiPodaciOLekaru() {
        return new Saglasnost.OVakcinaciji.PodaciOLekaru();
    }

    /**
     * Create an instance of {@link Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija }
     * 
     */
    public Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija createSaglasnostOVakcinacijiKontraindikacijePrivremenaKontraindikacija() {
        return new Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija();
    }

}
