//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 12:35:16 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.vakc-sistem.rs/saglasnost-za-imunizaciju",
        elementFormDefault = XmlNsForm.QUALIFIED,
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.vakc-sistem.rs/saglasnost-za-imunizaciju", prefix = ""),
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.vakc-sistem.rs/util", prefix = "util")
        }
)
package com.imunizacija.ImunizacijaApp.model.vakc_sistem.saglasnost_za_imunizaciju;

import javax.xml.bind.annotation.XmlNsForm;