//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.08 at 06:14:28 PM CET 
//


package com.imunizacija.ImunizacijaApp.model.vakc_sistem.saglasnost_za_imunizaciju;

import com.imunizacija.ImunizacijaApp.model.vakc_sistem.util.*;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Drzavljanstvo" type="{http://www.vakc-sistem.rs/util}Drzavljanstvo"/&gt;
 *         &lt;element name="Licni_podaci" type="{http://www.vakc-sistem.rs/util}Licni_podaci_detaljnije"/&gt;
 *         &lt;element name="Kontakt" type="{http://www.vakc-sistem.rs/util}Kontakt"/&gt;
 *         &lt;element name="Zaposlenje"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Radni_status"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.vakc-sistem.rs/util}Radni_status"&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Zanimanje"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Zdravstvena zastita"/&gt;
 *                         &lt;enumeration value="Socijalna zastita"/&gt;
 *                         &lt;enumeration value="Prosveta"/&gt;
 *                         &lt;enumeration value="MUP"/&gt;
 *                         &lt;enumeration value="Vojska RS"/&gt;
 *                         &lt;enumeration value="Drugo"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Socijalna_zastita" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Naziv_sedista"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Opstina_sedista"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Izjava"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Saglasan"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Da"/&gt;
 *                         &lt;enumeration value="Ne"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Imunoloski_lek"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="O_vakcinaciji" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Zdravstvena_ustanova"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Punkt"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Podaci_o_lekaru"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Ime"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;minLength value="2"/&gt;
 *                                   &lt;maxLength value="20"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Prezime"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;minLength value="2"/&gt;
 *                                   &lt;maxLength value="20"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Broj_telefona"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;pattern value="[0-9]{7,12}"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="Doza" type="{http://www.vakc-sistem.rs/util}Doza_detaljnije" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="Kontraindikacije" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="Privremena_kontraindikacija" maxOccurs="unbounded"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                         &lt;element name="Dijagnoza"&gt;
 *                                           &lt;simpleType&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                               &lt;minLength value="1"/&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/simpleType&gt;
 *                                         &lt;/element&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/restriction&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;element name="Odluka_komisije_o_trajnim" minOccurs="0"&gt;
 *                               &lt;simpleType&gt;
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                   &lt;enumeration value="Da"/&gt;
 *                                   &lt;enumeration value="Ne"/&gt;
 *                                 &lt;/restriction&gt;
 *                               &lt;/simpleType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "licniPodaci",
    "kontakt",
    "zaposlenje",
    "socijalnaZastita",
    "izjava",
    "datum",
    "oVakcinaciji"
})
@XmlRootElement(name = "Saglasnost")
public class Saglasnost {

    @XmlElement(name = "Drzavljanstvo", required = true)
    protected Drzavljanstvo drzavljanstvo;
    @XmlElement(name = "Licni_podaci", required = true)
    protected LicniPodaciDetaljnije licniPodaci;
    @XmlElement(name = "Kontakt", required = true)
    protected Kontakt kontakt;
    @XmlElement(name = "Zaposlenje", required = true)
    protected Saglasnost.Zaposlenje zaposlenje;
    @XmlElement(name = "Socijalna_zastita")
    protected Saglasnost.SocijalnaZastita socijalnaZastita;
    @XmlElement(name = "Izjava", required = true)
    protected Saglasnost.Izjava izjava;
    @XmlElement(name = "Datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(name = "O_vakcinaciji")
    protected Saglasnost.OVakcinaciji oVakcinaciji;
    @XmlAttribute(name = "Id", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger id;

    /**
     * Gets the value of the drzavljanstvo property.
     *
     * @return
     *     possible object is
     *     {@link Drzavljanstvo }
     *
     */
    public Drzavljanstvo getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     *
     * @param value
     *     allowed object is
     *     {@link Drzavljanstvo }
     *
     */
    public void setDrzavljanstvo(Drzavljanstvo value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the licniPodaci property.
     *
     * @return
     *     possible object is
     *     {@link LicniPodaciDetaljnije }
     *
     */
    public LicniPodaciDetaljnije getLicniPodaci() {
        return licniPodaci;
    }

    /**
     * Sets the value of the licniPodaci property.
     *
     * @param value
     *     allowed object is
     *     {@link LicniPodaciDetaljnije }
     *
     */
    public void setLicniPodaci(LicniPodaciDetaljnije value) {
        this.licniPodaci = value;
    }

    /**
     * Gets the value of the kontakt property.
     *
     * @return
     *     possible object is
     *     {@link Kontakt }
     *
     */
    public Kontakt getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     *
     * @param value
     *     allowed object is
     *     {@link Kontakt }
     *
     */
    public void setKontakt(Kontakt value) {
        this.kontakt = value;
    }

    /**
     * Gets the value of the zaposlenje property.
     *
     * @return
     *     possible object is
     *     {@link Saglasnost.Zaposlenje }
     *
     */
    public Saglasnost.Zaposlenje getZaposlenje() {
        return zaposlenje;
    }

    /**
     * Sets the value of the zaposlenje property.
     *
     * @param value
     *     allowed object is
     *     {@link Saglasnost.Zaposlenje }
     *
     */
    public void setZaposlenje(Saglasnost.Zaposlenje value) {
        this.zaposlenje = value;
    }

    /**
     * Gets the value of the socijalnaZastita property.
     *
     * @return
     *     possible object is
     *     {@link Saglasnost.SocijalnaZastita }
     *
     */
    public Saglasnost.SocijalnaZastita getSocijalnaZastita() {
        return socijalnaZastita;
    }

    /**
     * Sets the value of the socijalnaZastita property.
     *
     * @param value
     *     allowed object is
     *     {@link Saglasnost.SocijalnaZastita }
     *
     */
    public void setSocijalnaZastita(Saglasnost.SocijalnaZastita value) {
        this.socijalnaZastita = value;
    }

    /**
     * Gets the value of the izjava property.
     *
     * @return
     *     possible object is
     *     {@link Saglasnost.Izjava }
     *
     */
    public Saglasnost.Izjava getIzjava() {
        return izjava;
    }

    /**
     * Sets the value of the izjava property.
     *
     * @param value
     *     allowed object is
     *     {@link Saglasnost.Izjava }
     *
     */
    public void setIzjava(Saglasnost.Izjava value) {
        this.izjava = value;
    }

    /**
     * Gets the value of the datum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the oVakcinaciji property.
     *
     * @return
     *     possible object is
     *     {@link Saglasnost.OVakcinaciji }
     *
     */
    public Saglasnost.OVakcinaciji getOVakcinaciji() {
        return oVakcinaciji;
    }

    /**
     * Sets the value of the oVakcinaciji property.
     *
     * @param value
     *     allowed object is
     *     {@link Saglasnost.OVakcinaciji }
     *
     */
    public void setOVakcinaciji(Saglasnost.OVakcinaciji value) {
        this.oVakcinaciji = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Saglasan"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Da"/&gt;
     *               &lt;enumeration value="Ne"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Imunoloski_lek"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "saglasan",
        "imunoloskiLek"
    })
    public static class Izjava {

        @XmlElement(name = "Saglasan", required = true)
        protected String saglasan;
        @XmlElement(name = "Imunoloski_lek", required = true)
        protected String imunoloskiLek;

        /**
         * Gets the value of the saglasan property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getSaglasan() {
            return saglasan;
        }

        /**
         * Sets the value of the saglasan property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setSaglasan(String value) {
            this.saglasan = value;
        }

        /**
         * Gets the value of the imunoloskiLek property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getImunoloskiLek() {
            return imunoloskiLek;
        }

        /**
         * Sets the value of the imunoloskiLek property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setImunoloskiLek(String value) {
            this.imunoloskiLek = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Zdravstvena_ustanova"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Punkt"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Podaci_o_lekaru"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Ime"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;minLength value="2"/&gt;
     *                         &lt;maxLength value="20"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Prezime"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;minLength value="2"/&gt;
     *                         &lt;maxLength value="20"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Broj_telefona"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;pattern value="[0-9]{7,12}"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="Doza" type="{http://www.vakc-sistem.rs/util}Doza_detaljnije" maxOccurs="unbounded"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="Kontraindikacije" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="Privremena_kontraindikacija" maxOccurs="unbounded"&gt;
     *                       &lt;complexType&gt;
     *                         &lt;complexContent&gt;
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                               &lt;element name="Dijagnoza"&gt;
     *                                 &lt;simpleType&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                     &lt;minLength value="1"/&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/simpleType&gt;
     *                               &lt;/element&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/restriction&gt;
     *                         &lt;/complexContent&gt;
     *                       &lt;/complexType&gt;
     *                     &lt;/element&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;element name="Odluka_komisije_o_trajnim" minOccurs="0"&gt;
     *                     &lt;simpleType&gt;
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                         &lt;enumeration value="Da"/&gt;
     *                         &lt;enumeration value="Ne"/&gt;
     *                       &lt;/restriction&gt;
     *                     &lt;/simpleType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zdravstvenaUstanova",
        "punkt",
        "podaciOLekaru",
        "doze",
        "kontraindikacije"
    })
    public static class OVakcinaciji {

        @XmlElement(name = "Zdravstvena_ustanova", required = true)
        protected String zdravstvenaUstanova;
        @XmlElement(name = "Punkt", required = true)
        protected String punkt;
        @XmlElement(name = "Podaci_o_lekaru", required = true)
        protected Saglasnost.OVakcinaciji.PodaciOLekaru podaciOLekaru;
        @XmlElement(name = "Doza", required = true)
        protected List<DozaDetaljnije> doze;
        @XmlElement(name = "Kontraindikacije")
        protected Saglasnost.OVakcinaciji.Kontraindikacije kontraindikacije;

        /**
         * Gets the value of the zdravstvenaUstanova property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getZdravstvenaUstanova() {
            return zdravstvenaUstanova;
        }

        /**
         * Sets the value of the zdravstvenaUstanova property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setZdravstvenaUstanova(String value) {
            this.zdravstvenaUstanova = value;
        }

        /**
         * Gets the value of the punkt property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPunkt() {
            return punkt;
        }

        /**
         * Sets the value of the punkt property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPunkt(String value) {
            this.punkt = value;
        }

        /**
         * Gets the value of the podaciOLekaru property.
         *
         * @return
         *     possible object is
         *     {@link Saglasnost.OVakcinaciji.PodaciOLekaru }
         *
         */
        public Saglasnost.OVakcinaciji.PodaciOLekaru getPodaciOLekaru() {
            return podaciOLekaru;
        }

        /**
         * Sets the value of the podaciOLekaru property.
         *
         * @param value
         *     allowed object is
         *     {@link Saglasnost.OVakcinaciji.PodaciOLekaru }
         *
         */
        public void setPodaciOLekaru(Saglasnost.OVakcinaciji.PodaciOLekaru value) {
            this.podaciOLekaru = value;
        }

        /**
         * Gets the value of the doze property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the doze property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDoze().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DozaDetaljnije }
         *
         *
         */
        public List<DozaDetaljnije> getDoze() {
            if (doze == null) {
                doze = new ArrayList<DozaDetaljnije>();
            }
            return this.doze;
        }

        /**
         * Gets the value of the kontraindikacije property.
         *
         * @return
         *     possible object is
         *     {@link Saglasnost.OVakcinaciji.Kontraindikacije }
         *
         */
        public Saglasnost.OVakcinaciji.Kontraindikacije getKontraindikacije() {
            return kontraindikacije;
        }

        /**
         * Sets the value of the kontraindikacije property.
         *
         * @param value
         *     allowed object is
         *     {@link Saglasnost.OVakcinaciji.Kontraindikacije }
         *
         */
        public void setKontraindikacije(Saglasnost.OVakcinaciji.Kontraindikacije value) {
            this.kontraindikacije = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="Privremena_kontraindikacija" maxOccurs="unbounded"&gt;
         *             &lt;complexType&gt;
         *               &lt;complexContent&gt;
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                     &lt;element name="Dijagnoza"&gt;
         *                       &lt;simpleType&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                           &lt;minLength value="1"/&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/simpleType&gt;
         *                     &lt;/element&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/restriction&gt;
         *               &lt;/complexContent&gt;
         *             &lt;/complexType&gt;
         *           &lt;/element&gt;
         *         &lt;/sequence&gt;
         *         &lt;element name="Odluka_komisije_o_trajnim" minOccurs="0"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="Da"/&gt;
         *               &lt;enumeration value="Ne"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "privremeneKontraindikacije",
            "odlukaKomisijeOTrajnim"
        })
        public static class Kontraindikacije {

            @XmlElement(name = "Privremena_kontraindikacija", required = true)
            protected List<Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija> privremeneKontraindikacije;
            @XmlElement(name = "Odluka_komisije_o_trajnim")
            protected String odlukaKomisijeOTrajnim;

            /**
             * Gets the value of the privremeneKontraindikacije property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the privremeneKontraindikacije property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrivremeneKontraindikacije().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija }
             *
             *
             */
            public List<Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija> getPrivremeneKontraindikacije() {
                if (privremeneKontraindikacije == null) {
                    privremeneKontraindikacije = new ArrayList<Saglasnost.OVakcinaciji.Kontraindikacije.PrivremenaKontraindikacija>();
                }
                return this.privremeneKontraindikacije;
            }

            /**
             * Gets the value of the odlukaKomisijeOTrajnim property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOdlukaKomisijeOTrajnim() {
                return odlukaKomisijeOTrajnim;
            }

            /**
             * Sets the value of the odlukaKomisijeOTrajnim property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOdlukaKomisijeOTrajnim(String value) {
                this.odlukaKomisijeOTrajnim = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *         &lt;element name="Dijagnoza"&gt;
             *           &lt;simpleType&gt;
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *               &lt;minLength value="1"/&gt;
             *             &lt;/restriction&gt;
             *           &lt;/simpleType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datum",
                "dijagnoza"
            })
            public static class PrivremenaKontraindikacija {

                @XmlElement(name = "Datum", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datum;
                @XmlElement(name = "Dijagnoza", required = true)
                protected String dijagnoza;

                /**
                 * Gets the value of the datum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDatum() {
                    return datum;
                }

                /**
                 * Sets the value of the datum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDatum(XMLGregorianCalendar value) {
                    this.datum = value;
                }

                /**
                 * Gets the value of the dijagnoza property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDijagnoza() {
                    return dijagnoza;
                }

                /**
                 * Sets the value of the dijagnoza property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDijagnoza(String value) {
                    this.dijagnoza = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Ime"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;minLength value="2"/&gt;
         *               &lt;maxLength value="20"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Prezime"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;minLength value="2"/&gt;
         *               &lt;maxLength value="20"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Faksimil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Broj_telefona"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;pattern value="[0-9]{7,12}"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ime",
            "prezime",
            "faksimil",
            "brojTelefona"
        })
        public static class PodaciOLekaru {

            @XmlElement(name = "Ime", required = true)
            protected String ime;
            @XmlElement(name = "Prezime", required = true)
            protected String prezime;
            @XmlElement(name = "Faksimil", required = true)
            protected String faksimil;
            @XmlElement(name = "Broj_telefona", required = true)
            protected String brojTelefona;

            /**
             * Gets the value of the ime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIme() {
                return ime;
            }

            /**
             * Sets the value of the ime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIme(String value) {
                this.ime = value;
            }

            /**
             * Gets the value of the prezime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrezime() {
                return prezime;
            }

            /**
             * Sets the value of the prezime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrezime(String value) {
                this.prezime = value;
            }

            /**
             * Gets the value of the faksimil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFaksimil() {
                return faksimil;
            }

            /**
             * Sets the value of the faksimil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFaksimil(String value) {
                this.faksimil = value;
            }

            /**
             * Gets the value of the brojTelefona property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojTelefona() {
                return brojTelefona;
            }

            /**
             * Sets the value of the brojTelefona property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojTelefona(String value) {
                this.brojTelefona = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Naziv_sedista"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Opstina_sedista"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivSedista",
        "opstinaSedista"
    })
    public static class SocijalnaZastita {

        @XmlElement(name = "Naziv_sedista", required = true)
        protected String nazivSedista;
        @XmlElement(name = "Opstina_sedista", required = true)
        protected String opstinaSedista;

        /**
         * Gets the value of the nazivSedista property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivSedista() {
            return nazivSedista;
        }

        /**
         * Sets the value of the nazivSedista property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivSedista(String value) {
            this.nazivSedista = value;
        }

        /**
         * Gets the value of the opstinaSedista property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpstinaSedista() {
            return opstinaSedista;
        }

        /**
         * Sets the value of the opstinaSedista property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpstinaSedista(String value) {
            this.opstinaSedista = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Radni_status"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.vakc-sistem.rs/util}Radni_status"&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Zanimanje"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Zdravstvena zastita"/&gt;
     *               &lt;enumeration value="Socijalna zastita"/&gt;
     *               &lt;enumeration value="Prosveta"/&gt;
     *               &lt;enumeration value="MUP"/&gt;
     *               &lt;enumeration value="Vojska RS"/&gt;
     *               &lt;enumeration value="Drugo"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "radniStatus",
        "zanimanje"
    })
    public static class Zaposlenje {

        @XmlElement(name = "Radni_status", required = true)
        protected RadniStatus radniStatus;
        @XmlElement(name = "Zanimanje", required = true)
        protected String zanimanje;

        /**
         * Gets the value of the radniStatus property.
         * 
         * @return
         *     possible object is
         *     {@link RadniStatus }
         *     
         */
        public RadniStatus getRadniStatus() {
            return radniStatus;
        }

        /**
         * Sets the value of the radniStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link RadniStatus }
         *     
         */
        public void setRadniStatus(RadniStatus value) {
            this.radniStatus = value;
        }

        /**
         * Gets the value of the zanimanje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZanimanje() {
            return zanimanje;
        }

        /**
         * Sets the value of the zanimanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZanimanje(String value) {
            this.zanimanje = value;
        }

    }

}
