//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.11 at 05:46:05 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vakc-sistem.rs/korisnik", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.imunizacija.ImunizacijaApp.model.vakc_sistem.korisnik;
