//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 12:20:05 AM CET 
//


package com.sluzbenik.SluzbenikApp.model.vakc_sistem.potvrda_o_vakcinaciji;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.vakc_sistem.potvrda_o_vakcinaciji package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.vakc_sistem.potvrda_o_vakcinaciji
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji }
     * 
     */
    public PotvrdaOVakcinaciji createPotvrdaOVakcinaciji() {
        return new PotvrdaOVakcinaciji();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.PodaciOPrimaocu }
     * 
     */
    public PotvrdaOVakcinaciji.PodaciOPrimaocu createPotvrdaOVakcinacijiPodaciOPrimaocu() {
        return new PotvrdaOVakcinaciji.PodaciOPrimaocu();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.PodaciOVakcini }
     * 
     */
    public PotvrdaOVakcinaciji.PodaciOVakcini createPotvrdaOVakcinacijiPodaciOVakcini() {
        return new PotvrdaOVakcinaciji.PodaciOVakcini();
    }

    /**
     * Create an instance of {@link PotvrdaOVakcinaciji.PodaciOPotvrdi }
     * 
     */
    public PotvrdaOVakcinaciji.PodaciOPotvrdi createPotvrdaOVakcinacijiPodaciOPotvrdi() {
        return new PotvrdaOVakcinaciji.PodaciOPotvrdi();
    }

}
