//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.13 at 11:11:09 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vakc-sistem.rs/termini", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sluzbenik.SluzbenikApp.dto;
