//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.08 at 06:14:28 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://www.vakc-sistem.rs/zahtev-dzs",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.vakc-sistem.rs/zahtev-dzs", prefix = ""),
                @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.vakc-sistem.rs/util", prefix = "util")
        }
)
package com.imunizacija.ImunizacijaApp.model.vakc_sistem.zahtev_dzs;
