//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 10:57:53 PM CET 
//


package com.sluzbenik.SluzbenikApp.model.vakc_sistem.util;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.vakc_sistem.util package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.vakc_sistem.util
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link LicniPodaciJMBG }
     * 
     */
    public LicniPodaciJMBG createLicniPodaciJMBG() {
        return new LicniPodaciJMBG();
    }

    /**
     * Create an instance of {@link DozaSaUstanovom }
     * 
     */
    public DozaSaUstanovom createDozaSaUstanovom() {
        return new DozaSaUstanovom();
    }

    /**
     * Create an instance of {@link Drzavljanstvo }
     * 
     */
    public Drzavljanstvo createDrzavljanstvo() {
        return new Drzavljanstvo();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link LicniPodaciJMBGBrPasosa }
     * 
     */
    public LicniPodaciJMBGBrPasosa createLicniPodaciJMBGBrPasosa() {
        return new LicniPodaciJMBGBrPasosa();
    }

    /**
     * Create an instance of {@link LicniPodaciDetaljnije }
     * 
     */
    public LicniPodaciDetaljnije createLicniPodaciDetaljnije() {
        return new LicniPodaciDetaljnije();
    }

    /**
     * Create an instance of {@link Doza }
     * 
     */
    public Doza createDoza() {
        return new Doza();
    }

    /**
     * Create an instance of {@link DozaDetaljnije }
     * 
     */
    public DozaDetaljnije createDozaDetaljnije() {
        return new DozaDetaljnije();
    }

    /**
     * Create an instance of {@link Adresa.Ulica }
     * 
     */
    public Adresa.Ulica createAdresaUlica() {
        return new Adresa.Ulica();
    }

}
