//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.14 at 05:08:49 PM CET 
//


package com.imunizacija.ImunizacijaApp.model.vakc_sistem.odgovori;

import com.imunizacija.ImunizacijaApp.model.vakc_sistem.IdentifiableEntity;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Odgovor" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;sequence>
 *                     &lt;element name="Vakcina" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                   &lt;element name="Grad" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Termin" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Vrednost" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   &lt;element name="Ustanova" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Dodeljena_vakcina" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Razlog" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Email" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Indikator" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;minLength value="2"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "odgovori"
})
@XmlRootElement(name = "Odgovori")
public class Odgovori implements IdentifiableEntity {

    @XmlElement(name = "Odgovor", required = true)
    protected List<Odgovor> odgovori;

    /**
     * Gets the value of the odgovori property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the odgovori property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOdgovori().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Odgovor }
     * 
     * 
     */
    public List<Odgovor> getOdgovori() {
        if (odgovori == null) {
            odgovori = new ArrayList<Odgovor>();
        }
        return this.odgovori;
    }

    @Override
    public String getXmlId() {
        return null;
    }

    @Override
    public void setXmlId(String id) {

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;sequence>
     *           &lt;element name="Vakcina" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;/sequence>
     *         &lt;element name="Grad" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Termin" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Vrednost" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         &lt;element name="Ustanova" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Dodeljena_vakcina" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Razlog" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Email" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Indikator" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;minLength value="2"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vakcine",
        "grad",
        "termin",
        "vrednost",
        "ustanova",
        "dodeljenaVakcina",
        "razlog",
        "email"
    })
    @XmlRootElement(name = "Odgovor")
    public static class Odgovor {

        @XmlElement(name = "Vakcina", required = true)
        protected List<String> vakcine;
        @XmlElement(name = "Grad")
        protected String grad;
        @XmlElement(name = "Termin")
        protected String termin;
        @XmlElement(name = "Vrednost")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger vrednost;
        @XmlElement(name = "Ustanova")
        protected String ustanova;
        @XmlElement(name = "Dodeljena_vakcina")
        protected String dodeljenaVakcina;
        @XmlElement(name = "Razlog")
        protected String razlog;
        @XmlElement(name = "Email")
        protected String email;
        @XmlAttribute(name = "Indikator", required = true)
        protected String indikator;

        /**
         * Gets the value of the vakcine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVakcine() {
            if (vakcine == null) {
                vakcine = new ArrayList<String>();
            }
            return this.vakcine;
        }

        /**
         * Gets the value of the grad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGrad() {
            return grad;
        }

        /**
         * Sets the value of the grad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGrad(String value) {
            this.grad = value;
        }

        /**
         * Gets the value of the termin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermin() {
            return termin;
        }

        /**
         * Sets the value of the termin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermin(String value) {
            this.termin = value;
        }

        /**
         * Gets the value of the vrednost property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getVrednost() {
            return vrednost;
        }

        /**
         * Sets the value of the vrednost property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setVrednost(BigInteger value) {
            this.vrednost = value;
        }

        /**
         * Gets the value of the ustanova property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUstanova() {
            return ustanova;
        }

        /**
         * Sets the value of the ustanova property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUstanova(String value) {
            this.ustanova = value;
        }

        /**
         * Gets the value of the dodeljenaVakcina property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDodeljenaVakcina() {
            return dodeljenaVakcina;
        }

        /**
         * Sets the value of the dodeljenaVakcina property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDodeljenaVakcina(String value) {
            this.dodeljenaVakcina = value;
        }

        /**
         * Gets the value of the razlog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlog(String value) {
            this.razlog = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the indikator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndikator() {
            return indikator;
        }

        /**
         * Sets the value of the indikator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndikator(String value) {
            this.indikator = value;
        }

    }

}
