//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 10:57:53 PM CET 
//


package com.sluzbenik.SluzbenikApp.model.vakc_sistem.digitalni_zeleni_sertifikat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.sluzbenik.SluzbenikApp.model.vakc_sistem.util.DozaSaUstanovom;
import com.sluzbenik.SluzbenikApp.model.vakc_sistem.util.LicniPodaciJMBG;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Podaci_o_primaocu" type="{http://www.vakc-sistem.rs/util}Licni_podaci_JMBG"/&gt;
 *         &lt;element name="Podaci_o_sertifikatu"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Broj_sertifikata"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;pattern value="[0-9]{7}"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Datum_izdavanja_sertifikata" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                   &lt;element name="Qr_kod"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;minLength value="1"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Doza" type="{http://www.vakc-sistem.rs/util}Doza_sa_ustanovom" maxOccurs="unbounded"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOPrimaocu",
    "podaciOSertifikatu",
    "doze"
})
@XmlRootElement(name = "Digitalni_zeleni_sertifikat")
public class DigitalniZeleniSertifikat {

    @XmlElement(name = "Podaci_o_primaocu", required = true)
    protected LicniPodaciJMBG podaciOPrimaocu;
    @XmlElement(name = "Podaci_o_sertifikatu", required = true)
    protected DigitalniZeleniSertifikat.PodaciOSertifikatu podaciOSertifikatu;
    @XmlElement(name = "Doza", required = true)
    protected List<DozaSaUstanovom> doze;

    /**
     * Gets the value of the podaciOPrimaocu property.
     * 
     * @return
     *     possible object is
     *     {@link LicniPodaciJMBG }
     *     
     */
    public LicniPodaciJMBG getPodaciOPrimaocu() {
        return podaciOPrimaocu;
    }

    /**
     * Sets the value of the podaciOPrimaocu property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicniPodaciJMBG }
     *     
     */
    public void setPodaciOPrimaocu(LicniPodaciJMBG value) {
        this.podaciOPrimaocu = value;
    }

    /**
     * Gets the value of the podaciOSertifikatu property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalniZeleniSertifikat.PodaciOSertifikatu }
     *     
     */
    public DigitalniZeleniSertifikat.PodaciOSertifikatu getPodaciOSertifikatu() {
        return podaciOSertifikatu;
    }

    /**
     * Sets the value of the podaciOSertifikatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalniZeleniSertifikat.PodaciOSertifikatu }
     *     
     */
    public void setPodaciOSertifikatu(DigitalniZeleniSertifikat.PodaciOSertifikatu value) {
        this.podaciOSertifikatu = value;
    }

    /**
     * Gets the value of the doze property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the doze property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDoze().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DozaSaUstanovom }
     * 
     * 
     */
    public List<DozaSaUstanovom> getDoze() {
        if (doze == null) {
            doze = new ArrayList<DozaSaUstanovom>();
        }
        return this.doze;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Broj_sertifikata"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;pattern value="[0-9]{7}"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Datum_izdavanja_sertifikata" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *         &lt;element name="Qr_kod"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;minLength value="1"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojSertifikata",
        "datumIzdavanjaSertifikata",
        "qrKod"
    })
    public static class PodaciOSertifikatu {

        @XmlElement(name = "Broj_sertifikata", required = true)
        protected String brojSertifikata;
        @XmlElement(name = "Datum_izdavanja_sertifikata", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumIzdavanjaSertifikata;
        @XmlElement(name = "Qr_kod", required = true)
        protected String qrKod;

        /**
         * Gets the value of the brojSertifikata property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojSertifikata() {
            return brojSertifikata;
        }

        /**
         * Sets the value of the brojSertifikata property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojSertifikata(String value) {
            this.brojSertifikata = value;
        }

        /**
         * Gets the value of the datumIzdavanjaSertifikata property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumIzdavanjaSertifikata() {
            return datumIzdavanjaSertifikata;
        }

        /**
         * Sets the value of the datumIzdavanjaSertifikata property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumIzdavanjaSertifikata(XMLGregorianCalendar value) {
            this.datumIzdavanjaSertifikata = value;
        }

        /**
         * Gets the value of the qrKod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQrKod() {
            return qrKod;
        }

        /**
         * Sets the value of the qrKod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQrKod(String value) {
            this.qrKod = value;
        }

    }

}
