//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.04 at 10:57:53 PM CET 
//


package com.sluzbenik.SluzbenikApp.model.vakc_sistem.util;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Pol"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Musko"/&gt;
 *     &lt;enumeration value="Zensko"/&gt;
 *     &lt;enumeration value="Ostalo"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Pol")
@XmlEnum
public enum Pol {

    @XmlEnumValue("Musko")
    MUSKO("Musko"),
    @XmlEnumValue("Zensko")
    ZENSKO("Zensko"),
    @XmlEnumValue("Ostalo")
    OSTALO("Ostalo");
    private final String value;

    Pol(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Pol fromValue(String v) {
        for (Pol c: Pol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
